apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8086
  selector:
    app: influxdb
