image:
  repository: influxdb
  tag: "2.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8086

persistence:
  enabled: true
  storageClass: "-"
  accessMode: ReadWriteOnce
  size: 10Gi
